### PR TITLE
[PE-3860]: A blog about our Airflow upgrade journey

### PR DESCRIPTION
**Pull request by dimonchik-suvorov**
Here I've collected all main actions we have done, issues we have faced and solutions we have made during Airflow upgrade from version `2.2.0` to `2.5.3`

### CODE REVIEW

File: _posts/2023-06-07-airflow-upgrade-to-2-5-3.md [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+- airflow-series
+- aws
+  team: Data Platform
+---
+
+Let me continue QP's `airflow-series` rubric and tell you a story of one Airflow upgrade. In this post I'm going to describe what infrastructure we had before, how we improved it and what difficulties we faced along the way so let's go!
+
+### At the beginning there were...
+
+Main parts of our Airflow infrastructure:
```
Comment (dimonchik-suvorov) [inline _posts/2023-06-07-airflow-upgrade-to-2-5-3.md:16]: There is gonna be a high-level diagram of our infrastructure so people will understand it better and keep this image in minds while they will be reading

File: _posts/2023-06-07-airflow-upgrade-to-2-5-3.md [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+
+Finally, everything was tested and fixed. The time has come to upgrade Airflow on production! All DAGs paused, ECS tasks stopped. Production database snapshot created.
+
+###### Database migration
+We started applying migrations on production database. In order to do this we prepared another ECS task which runs `airfow db upgrade` command. We successfully deployed it via Terraform and start to wait... and wait... and wait a little bit more...
+
+After ~5 hours we started to think why it takes so long... We realized that:
+- our production Airflow database RDS cluster only twice as big as our development
+- we have giant database with data for 2017 year and so on (backfills mostly). Considering we had a `sentinel` DAG which checks Scheduler is alive for each 5 minutes (sends a gauge metric to the Datadog), and our main DAG with ~1k tasks in it running daily, you can imagine how big `task_instance` and `dag_run` tables were...
+- ???Missed index in the database
```
Comment (dimonchik-suvorov) [inline _posts/2023-06-07-airflow-upgrade-to-2-5-3.md:94]: @Maks-D @kuntalkumarbasu guys, please remind me what was the case, I already forgot((( what was that index that made our db migration slower

File: _posts/2023-06-07-airflow-upgrade-to-2-5-3.md [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+
+After that we've merged all PR's with updated DAGs and related services. Checked that there are no DAG parsing errors on production.
+
+Started all DAGs and start to observe... and it started to fail...
+- [Braking changes](https://github.com/apache/airflow/pull/26452/files#diff-55326294fdc9ce88aee820373ed658972dff4067517a9c4f59819efbbf3e3b85R27) in the SlackWebHook. Basically they refactored the hook and switched to the Slack SDK instead of using plain HTTP. This caused `SlackRequestError: Invalid URL detected: ***` for all our Slack hook usages. In order to fix it we had to went through all Slack Airflow Connections, copy `webhook_token` extra param, change the connection type to Slack Incoming Webhook and put copied value to the `Webhook Token` field
+- ???Bug in Databricks SQL operator they are creating new connection for each query. This breaks our templated queries because in most of them first query is `use some_database` and next is an actual processing query. But when it creates new connection for each query in a file it simply forgets about use statement and fails second query because can't find tables without database
```
Comment (dimonchik-suvorov) [inline _posts/2023-06-07-airflow-upgrade-to-2-5-3.md:113]: I don't like this point because I'd like to create an upstream PR with a fix first and then just put here a link to the upstream PR instead of describing it on fingers...

**Comment by dimonchik-suvorov** [comment]
Honestly I was trying to install it locally but something is going wrong and I'm trying to fix it:
```
$ sudo gem install bundler
Password:
Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6
```
Meanwhile please review the content of the blog while I'm trying to run it on my arm...

File: _posts/2023-06-07-airflow-upgrade-to-2-5-3.md [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+<font size="3"><center><i>Databricks cluster configuration parameters</i></center></font>
+
+Also, we have a couple of our own Airflow plugins like custom operators, hooks and _Self-Service Backfill UI_ (you can learn more about this in our [Airflow Summit 2021 slides](https://airflowsummit.org/slides/2021/e5_6-ModernizeAirflow-Scribd.pdf)). 
+And Jenkins pipeline for building Airflow docker image and apply Terraform to restart ECS tasks with new configurations and Airflow image.
+
+### Why?
+
+We decided to upgrade because of released features and fixed bugs obviously, but the most valuable thing we wanted is multiple Schedulers because our Fargate instance came close to it's max available resources, and we suffered from constant high CPU utilization.
+
+This caused MySQL upgrade because multiple Schedulers doesn't work with 5.7 which doesn't have that locking functionality we need...
```
Comment (Maks-D) [inline _posts/2023-06-07-airflow-upgrade-to-2-5-3.md:35]: Maybe we can add reason explicitly:
```suggestion
This caused MySQL upgrade because multiple Schedulers don't work with MySQL 5.7 which doesn't support SKIP LOCKED or NOWAIT SQL clauses.
```

File: _posts/2023-06-07-airflow-upgrade-to-2-5-3.md [hunk 5]
```diff
@@ -0,0 +1,131 @@
...
+
+Issues we knew about and/or caught during the testing were:
+- in our custom DAGs dump code - internal structure of the DAG class slightly changed (like `_BaseOperator__init_kwargs`, `TaskGroup`, `ParamsDict`, etc.), and it caused compilation errors
+- custom DAGs validations (DummyOperator deprecated in favor of EmptyOperator)
+- in custom operators `execute` function where we were suing TaskInstance `key` and it's changed to DagRun's `run_id`
+- some of `timetable` functions also changed, and we had to find new ways to do what we did before merging (like `dag.timetable.infer_data_interval(your_execution_date).end` became `dag.timetable.infer_manual_data_interval(run_after=exec_dt).start`)
+- `node:12.22.6` Docker image we used for building npm (`airflow/www/static/dist`) was too old for the new and shiny Airflow (switched to the `node:16.0.0`)
+- `TriggerRuleDep` changed, and our custom rules that were using/overriding `_get_dep_statuses` and `_evaluate_trigger_rule` also started to fail
+- Okta integration started to fail because of new Flask AppBuilder (simply adding `server_metadata_url` to existing configuration solved the issue)
```
Comment (Maks-D) [inline _posts/2023-06-07-airflow-upgrade-to-2-5-3.md:67]: I think here we can link to https://tech.scribd.com/blog/2021/integrating-airflow-and-okta.html
```suggestion
- [Okta integration](https://tech.scribd.com/blog/2021/integrating-airflow-and-okta.html) started to fail because of new Flask AppBuilder (simply adding `server_metadata_url` to existing configuration solved the issue)
```
